
const dictionaries = {
    'en': () => ({
        dataError: 'Error while getting data',  
        savedPreferences: 'Saved Preferences',
        apiError: 'Error connecting to the API.',
        nav: {
            home: 'Home',
            stockFinder: 'Stock Finder',
            news: 'News',
            contactUs: 'Contact Us',
            education: 'Education',
            community: 'Community'
        },
        userConfigurations: 'User Configuration',
        name: 'Name',
        language: 'Language',
        spanish: 'Spanish',
        english: 'English',

        welcome: (userName) => `Welcome to Financial Analyst ${userName}!`,
        welcometext: 'Here you can search for information about stocks, see their most important metrics and learn how to invest.',
        welcometext2: 'To get started, use our Stock Finder and write the symbol (ticker) of the stock that interests you. For example:',
        ExampleAplle: 'For Apple Inc',
        ExampleGoogle: 'For Alphabet (Google)',
        ExampleAmazon: 'For Amazon',
        ExampleTesla: 'For Tesla',
        welcometext3: "Then, we'll show you the most important financial metrics for that stock, including its current price, daily changes, dividend yield, and more. In addition, you will be able to see the latest news related to the company.",
        welcometext4: "If you want to learn more about the topic, go to the Education section where you will find explanations and videos.",

        MarcketStockList: 'Market Stock List',
        welcometext5: "View some of the most recent actions on the market:",
        
        loading: 'Loading...',
        ticker: 'Ticker',
        last: 'Last',
        change: 'Change',
        volume: 'Volume',

        /*Seccion de Stock Finder*/
        searchsymbol: 'Search Symbol',
        search: 'Search',
        stock: {
            dividendYield: 'Dividend yield',
            dividendPayoutRatio: 'Dividend payout ratio',
            debtToEquityRatio: 'Debt/Equity Ratio',
            priceToSales: 'Price/Sales Ratio',
            cashFlowPerShare: 'Cash flow per share',
            marketCap: 'Market capitalization',
            priceToBook: 'Price/Book Value Relationship',
            weekHigh52: 'Maximum 52 weeks',
            weekLow52: 'Minimum 52 weeks',
            notAvailable: 'Not available'
        },

        LatetsNews: 'Latest News',
        ShowMore: 'Show More',

        /*Seccion de News*/

        NewsText: `Here you can see the recent news related to the financial markets.`,

        /*Seccion de Contact Us*/

        contact: {
            title: 'Contact',
            description: 'You can contact us for more information or questions about our platform.',
            name: 'Name',
            email: 'Email'
        },

        /*Seccion de Education*/

        education: {
            title: 'Education',
            description: 'Here you can see educational material to understand the information.',
            terms: {
                per: 'It measures how many times investors are willing to pay for each unit of profit generated by the company.',
                roi: 'Evaluate the profitability of an investment.',
                roa: 'It shows how efficiently a company uses its assets.',
                roe: 'Measures profitability for shareholders.',
                marketCap: 'Total value of the company in the market.',
                dividendYield: 'Annual dividend yield of a company.',
                eps: 'Earnings for each share of the company.',
                pbRatio: 'Compare the market price to the book value.',
                beta: 'Measures the volatility of a stock compared to the market.'
            },
            videos: 'Educational Videos',
            videosDescription: 'Learn more about financial concepts and stock analysis with the following videos:',
            books: 'Recommended Books',
            bookDescriptions: {
                intelligentInvestor: 'by Benjamin Graham: Considered one of the best books on investing, it offers investing principles that have stood the test of time.',
                randomWalk: 'by Burton Malkiel: An accessible analysis of investing in stocks and how markets work.',
                millionaireMind: 'by T. Harv Eker: Explores the psychology of money and how our beliefs affect our ability to generate wealth.',
                yourMoney: 'by Joe Dominguez and Vicki Robin: A focus on the relationship between money and life, and how to better manage our finances.',
                buffettology: 'by Mary Buffett: This book explains with multiple real examples the techniques used by Warren Buffett, the investor who has turned $105,000 into $20 billion.',
                tradingInTheZone: 'by Mark Douglas: For Douglas, maximizing an appropriate mental attitude is key to achieving good results and turns out to be much more important than market analysis or the various systems that periodically become fashionable.'
            },
            seeOnAmazon: 'See on Amazon'
        },

        /*Seccion de Community*/

        CommunityText: `Share your opinions and comments with the community (remember to be respectful).`,
        Comment: `Write your comment here...`,
        AddComment: `Add Comment`
    }),
    'es': () => ({
        savedPreferences: 'Preferencias guardadas',
        nav: {
            home: 'Inicio',
            stockFinder: 'Buscador de acciones',
            news: 'Noticias',
            contactUs: 'Contáctenos',
            education: 'Educación',
            community: 'Comunidad'
        },
        userConfigurations: 'Configuraciones de usuario',
        name: 'Nombre',
        language: 'Idioma',
        spanish: 'Español',
        english: 'Inglés',

        welcome: (userName) => `¡Bienvenido a Financial Analyst ${userName}!`,
        welcometext: 'Aquí puedes buscar información sobre acciones, ver sus métricas más importantes y aprender a invertir.',
        welcometext2: 'Para comenzar, utiliza nuestro Buscador de Acciones y escribe el símbolo (ticker) de la acción que te interesa. Por ejemplo:',
        ExampleAplle: 'Para Apple Inc',
        ExampleGoogle: 'Para Alphabet (Google)',
        ExampleAmazon: 'Para Amazon',
        ExampleTesla: 'Para Tesla',
        welcometext3: "Luego, te mostraremos las métricas financieras más importantes para esa acción, incluido su precio actual, cambios diarios, rendimiento por dividendo y más. Además, podrás ver las últimas noticias relacionadas con la empresa.",
        welcometext4: "Si deseas aprender más sobre el tema, ve a la sección de Educación donde encontrarás explicaciones y videos.",

        MarcketStockList: 'Lista de Acciones del Mercado',
        welcometext5: "Mira algunas de las acciones más recientes en el mercado:",

        loading: 'Cargando...',
        ticker: 'Símbolo',
        last: 'Último',
        change: 'Cambio',
        volume: 'Volumen',

        /*Seccion de Stock Finder*/
        searchsymbol: 'Buscar Símbolo',
        search: 'Buscar',
        stock: {
            dividendYield: 'Rendimiento por dividendo',
            dividendPayoutRatio: 'Relación de pago de dividendos',
            debtToEquityRatio: 'Relación deuda/capital',
            priceToSales: 'Relación precio/ventas',
            cashFlowPerShare: 'Flujo de efectivo por acción',
            marketCap: 'Capitalización de mercado',
            priceToBook: 'Relación precio/valor en libros',
            weekHigh52: 'Máximo 52 semanas',
            weekLow52: 'Mínimo 52 semanas',
            notAvailable: 'No disponible'
        },

        LatetsNews: 'Últimas Noticias',
        ShowMore: 'Ver Más',

        /*Seccion de News*/

        NewsText: `Aquí puedes ver las noticias recientes relacionadas con los mercados financieros.`,

        /*Seccion de Contact Us*/

        contact: {
            title: 'Contacto',
            description: 'Puedes contactarnos para más información o preguntas sobre nuestra plataforma.',
            name: 'Nombre',
            email: 'Email'
        },

        /*Seccion de Education*/

        education: {
            title: 'Educación',
            description: 'Aquí puedes ver material educativo para entender la información.',
            terms: {
                per: 'Mide cuántas veces están dispuestos los inversores a pagar por cada unidad de beneficio generado por la empresa.',
                roi: 'Evalúa la rentabilidad de una inversión.',
                roa: 'Muestra qué tan eficientemente utiliza una empresa sus activos.',
                roe: 'Mide la rentabilidad para los accionistas.',
                marketCap: 'Valor total de la empresa en el mercado.',
                dividendYield: 'Rendimiento de dividendos anual de una empresa.',
                eps: 'Ganancias por cada acción de la empresa.',
                pbRatio: 'Compara el precio de mercado con el valor en libros.',
                beta: 'Mide la volatilidad de una acción en comparación con el mercado.'
            },
            videos: 'Videos Educativos',
            videosDescription: 'Aprende más sobre conceptos financieros y análisis de acciones con los siguientes videos:',
            books: 'Libros Recomendados',
            bookDescriptions: {
                intelligentInvestor: 'de Benjamin Graham: Considerado uno de los mejores libros sobre inversión, ofrece principios de inversión que han resistido la prueba del tiempo.',
                randomWalk: 'de Burton Malkiel: Un análisis accesible de la inversión en acciones y cómo funcionan los mercados.',
                millionaireMind: 'de T. Harv Eker: Explora la psicología del dinero y cómo nuestras creencias afectan nuestra capacidad para generar riqueza.',
                yourMoney: 'de Joe Dominguez y Vicki Robin: Se enfoca en la relación entre el dinero y la vida, y cómo gestionar mejor nuestras finanzas.',
                buffettology: 'de Mary Buffett: Este libro explica con múltiples ejemplos reales las técnicas utilizadas por Warren Buffett, el inversor que ha convertido $105,000 en $20 mil millones.',
                tradingInTheZone: 'de Mark Douglas: Para Douglas, maximizar una actitud mental adecuada es clave para lograr buenos resultados y resulta ser mucho más importante que el análisis de mercado o los diversos sistemas que periódicamente se ponen de moda.'
            },
            seeOnAmazon: 'Ver en Amazon'
        },

        /*Seccion de Community*/

        CommunityText: `Comparte tus opiniones y comentarios con la comunidad (recuerda ser respetuoso).`,
        Comment: `Escribe tu comentario aquí...`,
        AddComment: `Agregar Comentario`
    })

};

export const getDictionary = async (locale) => dictionaries[locale]();